name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Contribution Grid
        uses: Platane/snk@main
        with:
          github_user_name: haresh-r2103
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .  # Save in the root directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
